camera {

  # image width in pixels
  width  = 1944
  
  # image height in pixels
  height = 1472

  # Default exposure time in microseconds
  default_exposure-time-us = 10000.0

  # Default gain
  defaultGain = 1.0
}

pac-prototype-hcd {
  # Set to true to use synthetic Gaussian images without loading the native library.
  # Keep true for unit testing or when no physical camera is present.
  simulation-mode = true

  # Default GigE IP address of the Imperx C1911
  camera-ip = "192.168.1.100"

  # Default continuous stream frame period
  frame-period-millis = 1000
}
