csw-logging {
  # Log level for hcd
  component-log-levels {
    LGSF {
      Pacprototypehcd = info
    }
  }
}

# From Section 3.5.8.3, use the following configurations
# Connection information and configuration for the PAC.
# Name of optical element [enum: LOM, TPA, HEXFA1, HEXFA2, AGPA, AGCA, AGAM, AGFM, FM3, L1, L2]
# Beam index [scalar: 0 to 7 between LOM and AGAM, 0 otherwise]
# Target position in local coordinate (on the mirror surface) [vector of 2; unit: pixel].
# Range of beam motion in local coordinate [vector of 2; unit: pixel]
# Optional: Range of randomized beam target position in local coordinate
#   [vector of 2; unit: pixel] 7. Optional: Mapping matrix from mirror coordinate to a
#   reference coordinate and unit [matrix of 2x2]. Default to identity matrix if not supplied.

_detector = {
  xs = 32
  ys = 32
}

pac {
  optic {
    name = PROTO
    beamIndex = 0
    xLocalBeamTargetPositionInPixels = 400
    yLocalBeamTargetPositionInPixels = 400
    xBeamRangeInPixels = 100
    yBeamRangeInPixels = 100

  }
  camera {
    detectorDimensions = ${_detector}
  }
  data {
    writeDataToFile = false
  }
}