pac-prototype-hcd {
  # Set to true to use synthetic Gaussian images without loading the native library.
  # Keep true for unit testing or when no physical camera is present.
  simulation-mode = true

  # Default continuous stream frame period
  frame-period-millis = 1000

  vbds {
    # Enable publishing each frame to VBDS over HTTP as FITS bytes
    enabled = false

    # If true, try to create the stream on actor startup
    auto-create-stream = false
  }
}
