name = "BtoPrototypeContainer"
components: [
  {
    prefix = "LGSF.bto.prototypeAssembly"
    componentType = assembly
    componentHandlerClassName = "lgsf.btoprototypeassembly.BtoPrototypeAssemblyHandlers"
    locationServiceUsage = RegisterAndTrackServices
    connections = [
      {
        prefix: "LGSF.pac.prototypeHcd"
        componentType: hcd
        connectionType: pekko
      }
    ]
  },
  {
    prefix = "LGSF.pac.prototypeHcd"
    componentType = hcd
    componentHandlerClassName = "lgsf.pacprototypehcd.PacPrototypeHcdHandlers"
    locationServiceUsage = RegisterOnly
  }
]
